### ISSUE TITLE
ambiguous reference problem after porting to dotnet core

### ISSUE THREAD

**Issue by tdemir** [aws/porting-assistant-dotnet-client#1927]
## Describe the bug
In this example, I want to show a bug in aws porting assistant tools. Legacy dotnet projects show files that are included in csproj file, but new projects don’t store the file list. It shows all files in the folder.
When I try to port the legacy project to dotnet 7, it created an ambiguous reference problem.

### Expected behavior
As I understood, this tool should delete excluded csharp files before the porting process.

### Screenshots
![image](https://github.com/aws/porting-assistant-dotnet-client/assets/1425663/b6516ab2-2a8c-4194-b69e-49bd9954939c)

**Comment by birojnayak** [comment]
@tdemir thank you for reporting the bug. We are looking into the issue and will provide updates soon.

**Comment by birojnayak** [comment]
At this time we treat the excluded file as normal file(config/text file) and copy it as is, also there is no way to know deterministically for the tool that this file is excluded. We will look into the options for Include/Exclude MSBuild properties inside csproj/vbproj, but that would cover some scenarios , not all.
