### ISSUE TITLE
Add integration test for assesement result schema validation

### ISSUE THREAD

**Issue by ShanshanHe** [aws/porting-assistant-dotnet-client#440]
## Description
Add integration test for assesment result schema validation

## Solution idea(s)
Run json schema validation on assessment result including `package-analysis-result.json` and `api-analysis-result.json`.

**Comment by ShanshanHe** [comment]
PR here: https://github.com/aws/porting-assistant-dotnet-client/pull/441

**Comment by jonlouie** [comment]
Closing- completed by #441
