### ISSUE TITLE
There is mismatch between ApiAnalysisResults and RecommendedActions

### ISSUE THREAD

**Issue by irensaltali** [aws/porting-assistant-dotnet-client#51]
When I analyze this [repo](https://github.com/muratbaseren/Udemy-MyEvernote-Sample-Project.git), there is a recommendation about `System.Data.Entity` but it is not in `ApiAnalysisResults`. I think it should be reported as _INCOMPATIBLE_ in `ApiAnalysisResults` or there should not be any recommendation about that namespace.

Details:
Repo: https://github.com/muratbaseren/Udemy-MyEvernote-Sample-Project.git
Report file: `MyEvernoteSolution-analyze/solution-analyze/MyEvernote.WebApp/MyEvernote.WebApp-api-analysis.json`
Source File Name: CategoryController.cs

PS: I didn't have time to find the root cause. If I do, I will fix it and send a PR:

**Comment by flywanli** [comment]
Hi irensaltali, we have noticed that there is a missmatch for the entityframwork api in our code. So we recenlty push a PR https://github.com/aws/porting-assistant-dotnet-client/commit/e92114f04717b33c32d76662ade9911dfb25189e to fix it. Thanks for reporting this issues for us.
