### ISSUE TITLE
Error building application when multiple instances of msbuild are on machine

### ISSUE THREAD

**Issue by w-penberthy** [aws/porting-assistant-dotnet-client#584]
ERROR from log

Started process 50360: "**_C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe_**"  /noconsolelogger /p:RestorePackagesConfig=true /p:langversion=latest /restore /target:Clean;Build /property:ProvideCommandLineArgs="true";GenerateResourceMSBuildArchitecture="CurrentArchitecture";DesignTimeBuild="true";BuildProjectReferences="false";SkipCompilerExecution="true";DisableRarCache="true";AutoGenerateBindingRedirects="false";CopyBuildOutputToOutputDirectory="false";CopyOutputSymbolsToOutputDirectory="false";SkipCopyBuildProduct="true";AddModules="false";UseCommonOutputDirectory="true";GeneratePackageOnBuild="false";NonExistentFile="__NonExistentSubDir__\__NonExistentFile__";ResolveNuGetPackages="true";SolutionDir="C:\Source\nopCommerce-3.90\\" /l:BuildalyzerLogger,"C:\Users\w_pen\AppData\Local\Programs\Porting Assistant for .NET\resources\netcore_build\Buildalyzer.Logger.dll";2768;False "C:\Source\nopCommerce-3.90\Tests\Nop.Core.Tests\Nop.Core.Tests.csproj"
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.Process 50360 exited with code 1

I am using VS2019 for working with the solution, the VS2017 MSBuild was installed after the VS2019.

![error](https://user-images.githubusercontent.com/7268143/139343111-a18c8ead-e5f6-4645-84d4-3b8990cf47f0.png)
.

**Comment by jonlouie** [comment]
This was fixed in a previous PR. Please re-open if this issue persists.
