### ISSUE TITLE
PA file access denied error

### ISSUE THREAD

**Issue by Eruanion** [aws/porting-assistant-dotnet-client#88]
## Describe the bug
It appears that for every file in the project we attempt to write to a folder and if we do not have access rights to that folder every file will create an error in the logs (thousands potentially).

### Expected behavior
We should check access rights to the folder before attempting to write there.

### Desktop (please complete the following information)
 - OS: [e.g. Windows, macOS, Linux, etc]
 - Version/Distro: [e.g. 11, Big Sur, Ubuntu 18.04]

### Additional context
CustID: 486037472615 - 2,275 times each of the below errors:
('logs/486037472615/2021-05-12/default/portingAssistant-backend-logs/2021-05-12_17-06-32.log', '{"portingAssistantVersion":"1.5.1","targetFramework":"netcoreapp3.1","content":"[2021-05-12 22:35:33 ERR] (1.5.1) PortingAssistant.Client.PortingProjectFile.PortingProjectFileHandler: Error while parsing metadata file\\r\\nSystem.IO.IOException: Access to the path \'D:\\\\Manage\\\\Workspace\\\\Client\\\\ThinkBridge\' is denied.\\r\\n ---> System.UnauthorizedAccessException: Access to the path \'D:\\\\Manage\\\\Workspace\\\\Client\\\\ThinkBridge\' is denied.\\r\\n   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)\\r\\n   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)\\r\\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\\r\\n   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)\\r\\n   --- End of inner exception stack trace ---\\r\\n   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)\\r\\n   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)\\r\\n   at Codelyzer.Analysis.Build.ProjectBuildHandler.<>c__DisplayClass16_0.<LoadMetadataReferences>b__3(String fileRef)\\r\\n"}')

('logs/486037472615/2021-05-12/default/portingAssistant-backend-logs/2021-05-12_17-06-32.log', '{"portingAssistantVersion":"1.5.1","targetFramework":"netcoreapp3.1","content":"[2021-05-12 22:35:33 ERR] (1.5.1) PortingAssistant.Client.PortingProjectFile.PortingProjectFileHandler: Error while parsing metadata file\\r\\nSystem.IO.FileNotFoundException: Could not find a part of the path \'C:\\\\Users\\\\Anandan.Pattabhi\\\\AppData\\\\Local\\\\Programs\\\\Porting Assistant for .NET\\\\b-prepaid-migration-aws-port-nc\\\\packages\\\\AutoMapper.8.0.0\\\\lib\\\\net461\\\\AutoMapper.dll\'.\\r\\nFile name: \'b-prepaid-migration-aws-port-nc\\\\packages\\\\AutoMapper.8.0.0\\\\lib\\\\net461\\\\AutoMapper.dll\'\\r\\n ---> System.IO.DirectoryNotFoundException: Could not find a part of the path \'C:\\\\Users\\\\Anandan.Pattabhi\\\\AppData\\\\Local\\\\Programs\\\\Porting Assistant for .NET\\\\b-prepaid-migration-aws-port-nc\\\\packages\\\\AutoMapper.8.0.0\\\\lib\\\\net461\\\\AutoMapper.dll\'.\\r\\n   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)\\r\\n   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)\\r\\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\\r\\n   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)\\r\\n   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)\\r\\n   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)\\r\\n   at Codelyzer.Analysis.Build.ProjectBuildHandler.<>c__DisplayClass16_0.<LoadMetadataReferences>b__3(String fileRef)\\r\\n"}')

**Comment by cslong** [comment]
resolved with #103
